spring:
  profiles:
    active: local
  datasource:
    platform: H2
    url: jdbc:h2:mem:hyperdemo;Mode=Oracle;TRACE_LEVEL_SYSTEM_OUT=2
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: none