spring:
  profiles:
    active: local,h2

app:
  security:
    opa:
      apiDecisionUrl: http://localhost:8181/v1/data/api/allow

---
spring:
  config:
    activate:
      on-profile: unittest

app:
  security:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    platform: h2
    url: jdbc:h2:mem:hyperdemo;TRACE_LEVEL_SYSTEM_OUT=2;DB_CLOSE_ON_EXIT=FALSE
    continue-on-error: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

