spring:
  profiles:
    active: local,h2

---
spring:
  profiles: unittest

---
spring:
  profiles: local

---
spring:
  profiles: h2
  datasource:
    platform: h2
    url: jdbc:h2:mem:hyperdemo;Mode=Oracle;TRACE_LEVEL_SYSTEM_OUT=2;DB_CLOSE_ON_EXIT=FALSE
    continue-on-error: false
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: none
