
### create a task
POST /localhost:8080/tasks
authorization: Basic am9lOnBhc3N3b3Jk
content-type: application/vnd.siren+json

{
 "title": "creating an item",
  "description": "this is how you create an item",
  "importance": "normal",
  "due": "2021-05-16"
}


### get all tasks
GET /localhost:8080/tasks
accept: application/vnd.siren+json
authorization: Basic am9lOnBhc3N3b3Jk

###
DELETE http://localhost:8080/tasks/1
authorization: Basic am9lOnBhc3N3b3Jk

###
GET http://localhost:8080/tasks/1
#authorization: Basic am9lOnBhc3N3b3Jk

###
POST http://localhost:8080/tasks/1/complete
authorization: Basic am9lOnBhc3N3b3Jk
